const Icons = {
  Splash: require('../assets/Icon/Splash.png'),
  Splash1: require('../assets/Icon/Splash1.png'),
  image: require('../assets/Icon/image.png'),
  Bus: require('../assets/Icon/bus.png'),
  Exp: require('../assets/Icon/exp.png'),
  flights: require('../assets/Icon/flights.png'),
  hotls: require('../assets/Icon/hotls.png'),
  packages: require('../assets/Icon/packages.png'),
  train: require('../assets/Icon/train.png'),
  Logo: require('../assets/Icon/MainLogo.png'),
  round: require('../assets/Icon/round.png'),
  Google: require('../assets/Icon/google.png'),
  lady1: require('../assets/Images/lady1.png'),
  lady2: require('../assets/Images/lady2.png'),
  lady3: require('../assets/Images/lady3.png'),
  lady4: require('../assets/Images/lady4.png'),
  lady5: require('../assets/Images/lady5.png'),
  plane: require('../assets/Images/plane.png'),
  dummy: require('../assets/Images/dummy.png'),
};
export default Icons;
